name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.2
        
      - name: Run Unit Test Scripts 
        run: go test ./... -v
